---
sidebar: sidebar 
permalink: scpivs44_deploy_snapcenter_plug-in_for_vmware_vsphere.html 
keywords:  
summary: Para utilizar las funciones de SnapCenter con el fin de proteger máquinas virtuales, almacenes de datos y bases de datos consistentes con las aplicaciones en máquinas virtualizadas, se debe implementar el plugin de SnapCenter para VMware vSphere. 
---
= Ponga en marcha el plugin de SnapCenter para VMware vSphere
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Para utilizar las funciones de SnapCenter con el fin de proteger máquinas virtuales, almacenes de datos y bases de datos consistentes con las aplicaciones en máquinas virtualizadas, se debe implementar el plugin de SnapCenter para VMware vSphere.

.Antes de empezar
* Debe haber leído los requisitos de implementación.
+
El asistente de implementación no verifica los requisitos de espacio. Si no tiene espacio suficiente en el almacén de datos, la implementación puede verse correctamente, pero el dispositivo virtual no arranca.

* Debe ejecutar una versión compatible de vCenter Server.
* Debe haber configurado y configurado el entorno de vCenter Server.
* Debe haber configurado un host ESXi para la máquina virtual del plugin de VMware de SnapCenter.
* Debe haber descargado el archivo .ova del plugin de SnapCenter para VMware vSphere.
* Debe tener las credenciales de inicio de sesión en la instancia de vCenter Server.
* Debe haber cerrado sesión en vSphere Web Client y cerrado todas las sesiones del explorador para evitar cualquier problema con la caché del explorador durante la implementación del plugin de VMware de SnapCenter.
* Debe haber habilitado Transport Layer Security (TLS) en vCenter. Consulte la documentación de VMware.
* Puede implementar el complemento VMware de SnapCenter en la misma instancia de vCenter que el dispositivo virtual para VSC 7.x y versiones posteriores.
* Si piensa ejecutar backups en vCenter distinto de la donde se implementó el plugin de VMware de SnapCenter, el servidor ESXi, el complemento VMware de SnapCenter y cada instancia de vCenter deben sincronizarse al mismo tiempo.
* Para proteger las máquinas virtuales en almacenes de datos de VVol, primero se deben implementar herramientas de ONTAP para VMware vSphere. ONTAP Tools aprovisiona y configura el almacenamiento en ONTAP y en el cliente web de VMware.


Implemente el complemento VMware de SnapCenter en la misma zona horaria que vCenter. Las programaciones de backup se ejecutan en la zona horaria en la que se implementó el plugin de VMware de SnapCenter. VCenter informa de los datos en la zona horaria en la que se encuentra la instancia de vCenter. Por lo tanto, si el plugin de VMware de SnapCenter y vCenter están en zonas horarias diferentes, es posible que los datos de la consola del plugin de VMware de SnapCenter no sean los mismos que los datos de los informes.

.Pasos
. En el explorador, desplácese hasta VMware vSphere vCenter.
+

NOTE: Para los clientes web HTML de IPv6, debe usar Chrome o Firefox.

. En la pantalla de VMware, haga clic en *vSphere Web Client (HTML5)*.
. Inicie sesión en la página *VMware vCenter Single Sign-On*.
. En el panel de navegación, haga clic con el botón derecho del ratón en cualquier objeto de inventario que sea un objeto primario válido de una máquina virtual, como un centro de datos, clúster o host, y seleccione *implementar plantilla OVF* para iniciar el asistente de implementación de VMware.
. En la página *Seleccionar una plantilla OVF*, especifique la ubicación de `.ova` Archivo (como se muestra en la siguiente tabla) y haga clic en *Siguiente*.
+
|===
| Si ha descargado el `.ova` archivo a… | Haga esto… 


| Una ubicación en Internet | Introduzca la URL. Los orígenes de la URL compatibles son HTTP y HTTPS. 


| Un archivo local | Haga clic en *elegir archivos* y desplácese hasta el archivo .ova. 
|===
. En la página *Seleccione un nombre y una carpeta*, introduzca un nombre único para el equipo virtual o vApp, seleccione una ubicación de implementación y, a continuación, haga clic en *Siguiente*.
+
Este paso especifica dónde importar `.ova` Archivar en vCenter. El nombre predeterminado para la máquina virtual es el mismo que el nombre de la seleccionada `.ova` archivo. Si cambia el nombre predeterminado, elija un nombre único dentro de cada carpeta de máquina virtual de vCenter Server.

+
La ubicación predeterminada de implementación de la máquina virtual es el objeto de inventario donde comenzó el asistente.

. En la página *Seleccionar un recurso*, seleccione el recurso donde desea ejecutar la plantilla de VM desplegada y haga clic en *Siguiente*.
. En la página *revisar detalles*, compruebe la `.ova` Detalles de la plantilla y haga clic en *Siguiente*.
. En la página *acuerdos de licencia*, seleccione la casilla de verificación *Acepto todos los acuerdos de licencia*.
. En la página *Seleccionar almacenamiento*, defina dónde y cómo almacenar los archivos para la plantilla OVF implementada.
+
.. Seleccione el formato de disco para los VMDK.
.. Seleccione una política de almacenamiento de máquina virtual.
+
Esta opción solo está disponible si se habilitan las políticas de almacenamiento en el recurso de destino.

.. Seleccione un almacén de datos para almacenar la plantilla de OVA implementada.
+
El archivo de configuración y los archivos de disco virtual se almacenan en el almacén de datos.

+
Seleccione un almacén de datos lo suficientemente grande para acomodar la máquina virtual o vApp y todos los archivos de disco virtual asociados.



. En la página *Seleccionar redes*, haga lo siguiente:
+
.. Seleccione una red de origen y asígnela a una red de destino.
+
La columna Red de origen enumera todas las redes definidas en la plantilla OVA.

.. En la sección *Configuración de asignación IP*, seleccione el protocolo IP requerido y, a continuación, haga clic en *Siguiente*.
+
El plugin de SnapCenter para VMware vSphere es compatible con una interfaz de red. Si necesita varios adaptadores de red, debe configurarlo de forma manual. Consulte https://kb.netapp.com/Advice_and_Troubleshooting/Data_Protection_and_Security/SnapCenter/How_to_create_additional_network_adapters_in_NDB_and_SCV_4.3["Artículo de la base de conocimientos: Cómo crear adaptadores de red adicionales"^].



. En la página *Personalizar plantilla*, haga lo siguiente:
+
.. En la sección *Register to existing vCenter*, introduzca el nombre de vCenter y las credenciales de vCenter del dispositivo virtual.
+
En el campo *nombre de usuario de vCenter*, introduzca el nombre de usuario con formato `domain\username`.

.. En la sección *Crear credenciales de VCS*, introduzca las credenciales locales.
+
En el campo *Nombre de usuario*, introduzca el nombre de usuario local; no incluya los detalles del dominio.

+

IMPORTANT: Anote el nombre de usuario y la contraseña que especifique. Debe utilizar estas credenciales si desea modificar la configuración del plugin de VMware de SnapCenter más adelante.

.. En *Configurar propiedades de red*, introduzca el nombre de host.
+
... En la sección *Configurar propiedades de red IPv4*, introduzca la información de red como la dirección IPv4, la máscara de red IPv4, la puerta de enlace IPv4, el DNS primario IPv4, el DNS secundario IPv4, Y los dominios de búsqueda IPv4.
... En la sección *Configurar propiedades de red IPv6*, introduzca la información de red como la dirección IPv6, la máscara de red IPv6, la puerta de enlace IPv6, el DNS primario IPv6, el DNS secundario IPv6, Y dominios de búsqueda IPv6.
+
Seleccione los campos IPv4 o IPv6, o ambos, si corresponde. Si utiliza tanto IPv4 como IPv6, debe especificar el DNS primario solo para uno de ellos.

+

IMPORTANT: Puede omitir estos pasos y dejar las entradas en blanco en la sección *Propiedades de red de instalación*, si desea continuar con DHCP como configuración de red.



.. En *Fecha y hora de configuración*, seleccione la zona horaria en la que se encuentra el para vCenter.


. En la página *preparado para completar*, revise la página y haga clic en *Finalizar*.
+
Todos los hosts deben configurarse con direcciones IP (no se admiten los nombres de host FQDN). La operación de implementación no valida los datos antes de implementar.

+
Puede ver el progreso de la implementación desde la ventana tareas recientes mientras espera a que finalicen las tareas de importación e implementación de OVF.

+
Cuando el plugin de VMware de SnapCenter se implementa correctamente, se implementa como máquina virtual de Linux, está registrado en vCenter y se instala un cliente web de VMware vSphere.

. Vaya a la máquina virtual donde se implementó el complemento VMware de SnapCenter, haga clic en la ficha *Resumen* y, a continuación, haga clic en el cuadro *encendido* para iniciar el dispositivo virtual.
. Mientras el complemento VMware de SnapCenter se está encendiendo, haga clic con el botón derecho en el complemento VMware de SnapCenter implementado, seleccione *SO invitado* y, a continuación, haga clic en *instalar herramientas de VMware*.
+
VMware Tools se instala en la máquina virtual donde se pone en marcha el complemento VMware de SnapCenter. Para obtener más información sobre la instalación de VMware Tools, consulte la documentación de VMware.

+
Puede que la puesta en marcha tarde unos minutos en completarse. Una implementación correcta se indica cuando el plugin de VMware de SnapCenter está encendido, se instalan las herramientas de VMware y la pantalla le solicita que inicie sesión en el plugin de VMware de SnapCenter. Es posible cambiar la configuración de red de DHCP a estática durante el primer reinicio. Sin embargo, no se admite el cambio de static a DHCP.

+
La pantalla muestra la dirección IP donde se implementó el plugin de VMware de SnapCenter. Anote la dirección IP. Debe iniciar sesión en la GUI de gestión de plugins de VMware de SnapCenter si desea realizar cambios en la configuración de plugins de SnapCenter para VMware.

. Inicie sesión en la interfaz gráfica de usuario de la gestión del plugin de VMware de SnapCenter mediante la dirección IP que se muestra en la pantalla de implementación y con las credenciales que proporcionó en el asistente de implementación. A continuación, compruebe en la consola que el plugin de VMware de SnapCenter esté correctamente conectado a vCenter y esté habilitado.
+
Utilice el formato `https://<appliance-IP-address>:8080` Para acceder a la GUI de gestión.

+
De forma predeterminada, el nombre de usuario de la consola de mantenimiento se establece en “maint” y la contraseña se establece en “admin123”.

+
Si el plugin de VMware de SnapCenter no está habilitado, consulte link:scpivs44_restart_the_vmware_vsphere_web_client_service.html["Reinicie el servicio del cliente web de VMware vSphere"].

+
Si el nombre de host es 'UnifiedVSC/SCV, reinicie el dispositivo. Si al reiniciar el dispositivo no se cambia el nombre de host por el nombre de host especificado, debe reinstalar el dispositivo.



.Después de terminar
Debe completar el requerido link:scpivs44_post_deployment_required_operations_and_issues.html["operaciones posteriores a la implementación"].
