---
sidebar: sidebar 
permalink: scpivs44_manage_the_vmware_vsphere_web_client_service.html 
keywords:  
summary: Si el cliente web de VMware vSphere de SnapCenter comienza a comportarse de forma incorrecta, es posible que deba borrar la memoria caché del explorador. Si el problema persiste, reinicie el servicio del cliente web de VMware vSphere. 
---
= Reinicie el servicio del cliente web de VMware vSphere
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Si el cliente web de VMware vSphere de SnapCenter comienza a comportarse de forma incorrecta, es posible que deba borrar la memoria caché del explorador. Si el problema persiste, reinicie el servicio del cliente web de VMware vSphere.



== Reinicie el servicio del cliente web en una instancia de Linux vCenter

Si su instancia de vCenter está instalada en un dispositivo Linux, deberá utilizar comandos de Linux para reiniciar el servicio del cliente web de VMware vSphere de SnapCenter.

.Antes de empezar
Debe ejecutar vCenter 6.5 o una versión posterior.

.Pasos
. Utilice SSH para iniciar sesión en el dispositivo de vCenter Server como raíz.
. Acceda al shell del dispositivo o al shell BASH por medio del siguiente comando:
+
`shell`

. Detenga el servicio del cliente web por medio del siguiente comando HTML5:
+
`service-control --stop vsphere-ui`

. Elimine todos los paquetes de svm obsoletos de vCenter por medio del siguiente comando HTML5:
+
`etc/vmware/vsphere-ui/vc-packages/vsphere-client-serenity/rm -rf com.netapp.scvm.webclient-<version_number>`

+

IMPORTANT: No quite los paquetes VASA o VSC7.x y posteriores.

. Inicie el servicio del cliente web por medio del siguiente comando HTML5:
+
`service-control --start vsphere-ui`





== Reinicie el servicio del cliente web en una instancia de Windows vCenter

Si su instancia de vCenter está instalada en un host de Windows, debe utilizar comandos de Windows para reiniciar el servicio del cliente web de SnapCenter.

.Antes de empezar
Debe ejecutar vCenter 6.5 o una versión posterior.

.Pasos
. Detenga el servicio del cliente web por medio del siguiente comando HTML5:
+
`service-control --stop vsphere-ui`

+
Espere el mensaje `Completed Stop service request`.

. Elimine todos los paquetes de svm obsoletos que haya en vCenter siguiendo estos pasos:
+
.. Desplácese hasta la carpeta vCenter vsphere-client-Serenity/:
+
`C:\ProgramData\VMware\vCenterServer\cfg\vsphere-ui\vc-packages\vsphere-client-serenity\`

.. Elimine todas las carpetas de plugins que tengan el siguiente nombre:
+
`com.netapp.scvm.webclient-<version_number>.`



. Reinicie el servicio del cliente web por medio del siguiente comando HTML5:
+
`service-control --start vsphere-ui`

+
Espere el mensaje `Completed Start service request`.


